
#################################################
# Global test configuration
#################################################
config:

  # Define the metrics we are measuring
  metrics:
    - name: marathonUptime
      desc: Marathon uptime
      summarize: [mean, min, max]
      units: ms

    - name: marathonLeaderDuration
      desc: The duration since the last leader election happened in milliseconds
      summarize: [mean, min, max]
      units: ms

    - name: marathonAppCount
      desc: The number of apps in marathon
      summarize: [mean, min, max]
      units: count

    - name: marathonGroupCount
      desc: The number of groups in marathon
      summarize: [mean, min, max]
      units: count

    - name: marathonTasksCount
      desc: The number of tasks in marathon
      summarize: [mean, min, max]
      units: count

    - name: marathonTasksStaged
      desc: The number of tasks in marathon
      summarize: [mean, min, max]
      units: count

#################################################
# Tracker configuration
#################################################
trackers:

  # Re-route metrics collected from marathon to metrics being collected
  - class: tracker.DumpMetricTracker
    map:
      gauges.service.mesosphere.marathon.uptime.mean: marathonUptime
      gauges.service.mesosphere.marathon.leaderDuration.mean: marathonLeaderDuration
      gauges.service.mesosphere.marathon.app.count.mean: marathonAppCount
      gauges.service.mesosphere.marathon.group.count.mean: marathonGroupCount
      gauges.service.mesosphere.marathon.task.mean: marathonTasksCount
      gauges.service.mesosphere.marathon.task.staged.count.mean: marathonTasksStaged
