
#################################################
# Global test configuration
#################################################
config:

  # Define the metrics we are measuring
  metrics:
    - name: marathonSysCpuWait
      desc: CPU time spent waiting
      summarize: [mean, min, max]
      units: "?"

    - name: marathonSysCpuSystem
      desc: CPU time spent on system tasks
      summarize: [mean, min, max]
      units: "?"

    - name: marathonSysCpuUser
      desc: CPU time spent on user tasks
      summarize: [mean, min, max]
      units: "?"

#################################################
# Tracker configuration
#################################################
trackers:

  # Re-route metrics collected from marathon to metrics being collected
  - class: tracker.DumpMetricTracker
    map:
      system-metric.cpu.cpu-wait.p50: marathonSysCpuWait
      system-metric.cpu.cpu-system.p50: marathonSysCpuSystem
      system-metric.cpu.cpu-user.p50: marathonSysCpuUser
