
#################################################
# Global test configuration
#################################################
config:

  # We require datadog credentials to be given through the command-line
  definitions:
    - name: datadog_api_key
      desc: The datadog API Key
      required: yes
    - name: datadog_app_key
      desc: The datadog App Key
      required: yes

#################################################
# Global test configuration
#################################################
reporters:

  - class: reporter.DataDogReporter
    api_key: "{{datadog_api_key}}"
    app_key: "{{datadog_app_key}}"
    prefix: "marathon.perf."
    points:
      - name: meanDeploymentTime
        indicator: meanDeploymentTime
      - name: meanHttpRequestTime
        indicator: meanHttpRequestTime
