
#################################################
# Global test configuration
#################################################
reporters:

  # Create plots as images to results/plot-*.png
  - class: reporter.PlotReporter
    xscale: log2
    prefix: results/plot-
